export function getDom() {
  const byId = (id) => document.getElementById(id);

  return {
    container: byId("canvas-container"),
    loading: byId("loading"),
    nav: document.querySelector(".af-nav"),
    appShell: byId("af-app-shell"),

    renderToggle: byId("af-render-toggle"),
    renderKolam: byId("af-render-kolam"),
    renderHalo: byId("af-render-halo"),
    renderLayered: byId("af-render-layered"),
    hallResetBtn: byId("af-hall-reset"),

    toggleBtn: byId("settings-toggle"),
    effectPanel: byId("effect-panel"),

    fileInput: byId("fileInput"),
    backBtn: byId("back-btn"),
    prevZone: byId("prev-zone"),
    nextZone: byId("next-zone"),

    controlPanel: byId("control-panel"),
    previewToggle: byId("af-preview-toggle"),
    previewExit: byId("af-preview-exit"),
    galleryUI: byId("gallery-ui"),
    galleryCounter: byId("gallery-counter"),

    agentPill: byId("af-agent-pill"),
    languageChip: byId("af-language-chip"),
    languageMenu: byId("af-language-menu"),
    languageMenuTitle: byId("af-language-menu-title"),
    langZhBtn: byId("af-lang-zh"),
    langEnBtn: byId("af-lang-en"),
    centerStage: byId("af-center-stage"),
    stageStack: byId("af-stage-stack"),
    typingIndicator: byId("af-typing-indicator"),
    homeVoice: byId("af-memory-input") || byId("af-home-voice"),
    homePrompt: byId("af-home-prompt"),
    userBubble: byId("af-user-bubble"),
    micBtn: byId("mic-btn") || byId("af-mic-btn"),
    voiceTimer: byId("af-voice-timer"),
    saveMemoryBtn: byId("af-save-memory"),
    closeVoiceBtn: byId("af-close-voice"),
    memoryInput: byId("memory-input"),
    inputWrapper: byId("input-wrapper"),
    audioWave: byId("audio-wave"),
    statusText: byId("status-text"),
    outputDisplay: byId("output-display"),
    micIcon: byId("mic-icon"),
    stopIcon: byId("stop-icon"),

    navHall: document.querySelector('[data-action="open-hall"]'),
    navCalendar: document.querySelector('[data-action="open-calendar"]'),
    calendarBackHomeBtn: byId("calendar-back-home"),

    diaryModal: byId("af-diary-modal"),
    diaryModalDate: byId("af-modal-date"),
    diaryModalTime: byId("af-modal-time"),
    diaryModalMood: byId("af-modal-mood"),
    diaryModalTitle: byId("af-modal-title"),
    diaryModalSubtitle: byId("af-modal-subtitle"),
    diaryModalContent: byId("af-modal-content"),
    diaryModalAiText: byId("af-modal-ai-text"),
    diaryModalTags: byId("af-modal-tags"),
    diaryModalClose: byId("af-modal-close"),
    diaryModalShare: byId("af-modal-share"),

    landingRoot: byId("af-landing"),
    landingUploadBtn: byId("af-landing-upload"),
    blocker: byId("af-save-blocker"),
    blockerText: byId("af-blocker-text"),

    // sliders
    sliders: {
      brightness: { input: byId("inp-brightness"), label: byId("val-brightness") },
      contrast: { input: byId("inp-contrast"), label: byId("val-contrast") },
      particleSize: { input: byId("inp-particleSize"), label: byId("val-particleSize") },
      gridOpacity: { input: byId("inp-gridOpacity"), label: byId("val-gridOpacity") },
      erosionSpeed: { input: byId("inp-erosionSpeed"), label: byId("val-erosionSpeed") },
      waveAmplitude: { input: byId("inp-waveAmplitude"), label: byId("val-waveAmplitude") },
      waveSpeed: { input: byId("inp-waveSpeed"), label: byId("val-waveSpeed") },
      dispersion: { input: byId("inp-dispersion"), label: byId("val-dispersion") },
      edgeRoughness: { input: byId("inp-edgeRoughness"), label: byId("val-edgeRoughness") },
      stableRadius: { input: byId("inp-stableRadius"), label: byId("val-stableRadius") },
      homeZoom: { input: byId("af-home-zoom"), label: byId("val-home-zoom") },
      homeYOffset: { input: byId("af-home-y"), label: byId("val-home-y") },
    },
  };
}
